[character]
success_symbol = '[á… ](bold green)'
error_symbol = '[ğŸ—´ ](bold red)'

[battery]
charging_symbol = 'ï•¼ âš¡ï¸'
discharging_symbol = 'ï•¼ '
unknown_symbol = 'ï•¼ ? '

[[battery.display]]
threshold = 15
style = 'bold red'

[[battery.display]]  
threshold = 35
style = 'bold yellow'

[[battery.display]] 
threshold = 100
style = 'bold green'
discharging_symbol = 'ï•¼ '

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[golang]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'
