[character]
success_symbol = '[á… ](bold green)'
error_symbol = '[ğŸ—´ ](bold red)'

[battery]
charging_symbol = 'ğŸ”‹âš¡ï¸'
discharging_symbol = 'ğŸ”‹ '
unknown_symbol = 'ğŸ”‹? '

[[battery.display]]
threshold = 15
style = 'bold red'

[[battery.display]]  
threshold = 35
style = 'bold yellow'

[[battery.display]] 
threshold = 100
style = 'bold green'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'
